[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "/pages/auth/auth.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/pages/auth/signup.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sem1"
  to = "/pages/semesters/sem1.html"
  status = 200

[[redirects]]
  from = "/sem2"
  to = "/pages/semesters/sem2.html"
  status = 200

[[redirects]]
  from = "/sem3"
  to = "/pages/semesters/sem3.html"
  status = 200

[[redirects]]
  from = "/sem4"
  to = "/pages/semesters/sem4.html"
  status = 200

[[redirects]]
  from = "/library"
  to = "/pages/library.html"
  status = 200

[[redirects]]
  from = "/courses"
  to = "/pages/courses.html"
  status = 200

[[redirects]]
  from = "/tools"
  to = "/pages/tools.html"
  status = 200

[[redirects]]
  from = "/dsa"
  to = "/pages/dsa/visual-dsa.html"
  status = 200

[[redirects]]
  from = "/os"
  to = "/pages/os/os-visual.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/pages/auth/auth.html"
  status = 302
